### ISSUE TITLE
[Request] Don't require ModMenu

### ISSUE THREAD

**Issue by sisby-folk** [Draradech/SimpleFogControl#1]
Hey there! I'm currently using an edited jar of this mod, because I don't have modmenu, and the mod runs fine without it.
The settings can be edited through the json just fine, but personally I'm using [modsettings](https://modrinth.com/mod/mod-settings) which provides similar functionality to modmenu without showing all mods.

Would it be possible for the official release to drop the requirement?

**Comment by Draradech** [comment]
Dropped dependency in the 1.19 branch (not released yet). Do you think it's worth the effort to also update the 1.18.2 version, or is 1.19 fine?

**Comment by sisby-folk** [comment]
I'm using 1.18.2 for my pack, and I always prefer less JAR redistribution!

**Comment by Draradech** [comment]
fixed in v1.2.1 for 1.18.2
