### ISSUE TITLE
Crashes when loading a world in 1.20.5

### ISSUE THREAD

**Issue by J4PC** [Draradech/SimpleFogControl#12]
![image](https://github.com/Draradech/SimpleFogControl/assets/97805057/b8a21335-5594-4f67-a923-777abf9377ab)

> The game crashed whilst unexpected error
> Error: java.lang.NoSuchFieldError: Class net.minecraft.class_1294 does not have member field 'net.minecraft.class_1291 field_5919'

farbic-loader-0.15.10-1.20.5 **using the mods:** 
- simplefog-1.4.0
- cloth-config-14.0.126-fabric
- fabric-api-0.97.6+1.20.5

**Comment by Draradech** [comment]
updated to 1.20.6 today
