### ISSUE TITLE
Failed to load config menu w/ Mod Menu

### ISSUE THREAD

**Issue by daevydwakesburrow** [Draradech/SimpleFogControl#13]
I'm having a problem the mod as it seems to not want to mesh with Mod Menu mod. The configuration screen fails to load with Mod Menu:

Message received:
Failed to load config screen for 'simplefog'
Report to 'simplefog', not Mod Menu

java.lang.NoSuchMethodError: 'void
net.minecraft.class_2960.<init>(java.lang.String)'

I'm not entirely certain if it's something on my end or the mod's program end. I am woefully ignorant when it comes to programming...

**Comment by Draradech** [comment]
That looks like a version conflict. Which mod versions (simplefog and modmenu) and minecraft version are you on?
1.21(.1) should use 1.6.0 of simplefog and 11.0.x of modmenu.

**Comment by daevydwakesburrow** [comment]
I'm on 11.0.2 of modmenu and 1.6.0 of simplefog

**Comment by Draradech** [comment]
That's strange. That exact combination is working fine here.

Am 23. September 2024 22:22:45 MESZ schrieb daevydwakesburrow ***@***.***>:

**Comment by daevydwakesburrow** [comment]
ok I did miss a part of the error message
the full message:

java.lang.NoSuchMethodError:'voidnet.minecraftclass_2960.<init>(java.lang.String)'

**Comment by Draradech** [comment]
2960 is net.minecraft.util.Identifier. I don't touch that directly from my code, so it might be cloth config API. Should be version 15.0.130 or 140 for 1.21.x (I tested with 130, but 140 is the up to date one).

**Comment by daevydwakesburrow** [comment]
okay that seems to be it, I'm on 14.0.129. I'll update it and see what happens

**Comment by daevydwakesburrow** [comment]
Yup, there it is! Thanks for your help!
