### ISSUE TITLE
Incompatibility with 1.21.3

### ISSUE THREAD

**Issue by J4PC** [Draradech/SimpleFogControl#14]
**The game crashes when loading a world in 1.21.3**

farbic-loader-0.16.7-1.21.3 using the mods:
-     simplefog-1.6.0
-     cloth-config-16.0.141-fabric
-     fabric-api-0.106.1+1.21.3

> The game crashed whilst unexpected error
> Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_758 failed

**Comment by Draradech** [comment]
The update is non-trivial. Mojang changed stuff around the fog, presumably for the creaking and/or pale garden. I'm, looking into it, no ETA.

**Comment by Draradech** [comment]
Wasn't quite as bad as I thought. Update is live here and on modrinth, curseforge is processing.
