### ISSUE TITLE
SimpleFog does not blend entities in the fog

### ISSUE THREAD

**Issue by coornio** [Draradech/SimpleFogControl#2]
![image](https://user-images.githubusercontent.com/11655762/175173744-a7916d2a-0b1a-4127-a65d-e9c43299d14a.png)

This is a shot underwater, since the fog is pretty thick. It happens in all situations where fog is involved though. Any entities, whether they're mobs, pickup items, or block entities (chests, etc), they all fail to be shaded by the fog when this mod is enabled.

Can you please investigate this further? I love the fog control so that it actually has some depth, but this is a rather jarring downside :)

**Comment by Draradech** [comment]
![2022-06-23_12 53 03](https://user-images.githubusercontent.com/223321/175283351-90287639-a9e3-4af9-8b3c-ef98af60c179.png)
![2022-06-23_12 55 01](https://user-images.githubusercontent.com/223321/175283386-b82fc5bd-9629-40e4-bd63-ce3368cf6455.png)
Can not reproduce. Tried with only SimpleFog and with Sodium + SimpleFog.
Probably a mod conflict. Can you send your modlist?

**Comment by coornio** [comment]
Hmm, then perhaps I screwed up in my earlier attempt to isolate it. I'll give it another go. Current modlist is.. uhh. Big.

![image](https://user-images.githubusercontent.com/11655762/175296265-d4e06c5f-349c-47b5-a195-8537a58b98ea.png)

Will do some more testing and return shortly. Let me know though if anything in particular catches your eye.

**Comment by coornio** [comment]
Update -- can't seem to get it to happen anymore. Took off all mods and added them back in bunches, never noticed this happening again, even after everything was added back on.

Don't know what to think of this. I'll close for now unless I can reliably figure out what triggers it next time it happens.
