### ISSUE TITLE
SFC is not compatible with its dependencie (cloth config api 8.0.75)

### ISSUE THREAD

**Issue by Wayturns** [Draradech/SimpleFogControl#3]
as said SFC is not compatible with CCA 8.0.75 which it needs to work please fix it

![unknown](https://user-images.githubusercontent.com/92233613/185709840-2be22230-186b-4935-a9c0-9687c3dc78ee.png)
![image](https://user-images.githubusercontent.com/92233613/185709915-9329505c-9262-41cb-85ab-cbef99fffee0.png)

**Comment by Draradech** [comment]
It looks like modrinth's dependency resolution needs some work. I changed it manually to a fixed version (7.0.74), but any 7.x version will work for now.
I'll run some tests, I may be able to relax the dependency to >= 7.x, then 8.x versions should work as well.

**Comment by Draradech** [comment]
v1.3.1 is up. working with cloth-config 7 (on 1.19) or 8 (on 1.19, 1.19.1 or 1.19.2)
