### ISSUE TITLE
Very rapid flashing on config screen

### ISSUE THREAD

**Issue by naturalobject** [Draradech/SimpleFogControl#7]
When trying to edit settings, the whole row flashes white constantly (faster than shown in the GIF). This can be dangerous for people experiencing epilepsy.
![Animation](https://user-images.githubusercontent.com/130379566/236580861-ff727d74-e873-4f5e-81b6-e320edcb705e.gif)

**Comment by Draradech** [comment]
I can't reproduce this. In fact, I have no control over the rendering of the options menu at all. Not sure if this is cloth config or modmenu. In any case, it looks like you have more mods affecting rendering (I can at least see that something has modified font rendering), so it's probably a mod interaction.
